# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
