# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0002_video_video_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='scripted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='shot',
            field=models.BooleanField(default=False),
        ),
    ]
